from dataclasses import dataclass
from datapyrse.query._condition_expression import ConditionExpression as ConditionExpression
from enum import StrEnum

class FilterOperator(StrEnum):
    AND = 'AND'
    OR = 'OR'

@dataclass
class FilterExpression:
    filter_operator: FilterOperator = ...
    conditions: list[ConditionExpression] = ...
    filters: list['FilterExpression'] = ...
    def __post_init__(self) -> None: ...
    def __init__(self, filter_operator=..., conditions=..., filters=...) -> None: ...
