from dataclasses import dataclass

@dataclass
class OptionSet:
    label: str | None = ...
    value: int | None = ...
    def to_dict(self) -> dict[str, str | int | None]: ...
    def get_option_value(self) -> int | None: ...
    def get_option_label(self) -> str | None: ...
    def __init__(self, label=..., value=...) -> None: ...
