from dataclasses import dataclass
from datapyrse.query._column_set import ColumnSet as ColumnSet
from datapyrse.query._condition_expression import ConditionOperator as ConditionOperator
from datapyrse.query._filter_expression import FilterExpression as FilterExpression
from datapyrse.query._link_entity import LinkEntity as LinkEntity
from datapyrse.query._order_expression import OrderExpression as OrderExpression

@dataclass
class QueryExpression:
    entity_name: str
    column_set: ColumnSet
    criteria: FilterExpression | None = ...
    orders: list[OrderExpression] | None = ...
    link_entities: list[LinkEntity] | None = ...
    top_count: int | None = ...
    distinct: bool = ...
    fetch_xml: str = ...
    def __post_init__(self) -> None: ...
    def __init__(self, entity_name, column_set, criteria=..., orders=..., link_entities=..., top_count=..., distinct=...) -> None: ...
