from dataclasses import dataclass
from datapyrse._entity import Entity as Entity

@dataclass
class EntityCollection:
    entity_logical_name: str | None = ...
    entities: list[Entity] | None = ...
    def __post_init__(self) -> None: ...
    def add_entity(self, entity: Entity) -> None: ...
    def remove_entity(self, entity: Entity) -> None: ...
    def to_dict(self) -> dict[str, str | list[dict[str, str]]]: ...
    def __init__(self, entity_logical_name=..., entities=...) -> None: ...
