from dataclasses import dataclass
from uuid import UUID

@dataclass
class EntityReference:
    entity_logical_name: str
    entity_id: UUID | None = ...
    name: str | None = ...
    def __post_init__(self) -> None: ...
    def to_dict(self) -> dict[str, str]: ...
    def __init__(self, entity_logical_name, entity_id=..., name=...) -> None: ...
