from dataclasses import dataclass
from datapyrse._entity_reference import EntityReference as EntityReference

@dataclass
class EntityReferenceCollection:
    entity_logical_name: str
    entity_references: list[EntityReference]
    def __post_init__(self) -> None: ...
    def __len__(self) -> int: ...
    def add(self, entity_reference: EntityReference) -> None: ...
    def remove(self, entity_reference: EntityReference) -> None: ...
    def __init__(self, entity_logical_name, entity_references) -> None: ...
