from dataclasses import dataclass
from datapyrse._entity_reference import EntityReference as EntityReference
from datapyrse.query._option_set import OptionSet as OptionSet
from logging import Logger
from typing import Any
from uuid import UUID

@dataclass
class Entity:
    entity_logical_name: str
    entity_id: UUID | None = ...
    attributes: dict[str, Any] = ...
    logger: Logger = ...
    def __post_init__(self) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __init__(self, entity_logical_name, entity_id=..., attributes=..., logger=...) -> None: ...
